-- Original player-led chapters. {dragon} is filled with the selected owned
-- dragon's name in the client; the book adaptation remains a separate chapter.
INSERT INTO public.story_nodes
  (chapter_id, node_key, stage_number, node_type, title, description, body_text,
   speaker, options, state_changes, rewards, is_start, is_published)
VALUES
  ('my_dragon', 'arrival', 1, 'scene', '새로운 초대', '당신의 모험이 시작됩니다.',
   '당신은 성의 훈련장에 도착합니다. 그리피스는 드래곤 스톤이 당신에게 반응했다고 말합니다. 보, 아나, 로리가 옆에서 기다립니다. 하지만 어떤 드래곤이 당신의 동료가 될지는 아직 아무도 모릅니다.',
   '내레이터',
   '[{"label":"드래곤들을 만나러 간다","next_node":"meeting","state_changes":{"Courage":1}}]'::jsonb,
   '{}'::jsonb, '{}'::jsonb, true, true),
  ('my_dragon', 'meeting', 2, 'scene', '첫 만남', '나의 드래곤을 만납니다.',
   '조용한 우리 앞에서 {dragon}이(가) 당신을 바라봅니다. 다가오라고 재촉하지도, 달아나지도 않습니다. 당신은 몸을 낮추고 {dragon}이(가) 먼저 선택할 시간을 줍니다.',
   '내레이터',
   '[{"label":"손을 내밀고 기다린다","next_node":"trust","state_changes":{"Bond":2}},{"label":"조금 떨어져 눈높이를 맞춘다","next_node":"trust","state_changes":{"Bond":1,"Patience":1}}]'::jsonb,
   '{}'::jsonb, '{}'::jsonb, false, true),
  ('my_dragon', 'trust', 3, 'scene', '서로의 신호', '강요하지 않는 첫 교감.',
   '{dragon}이(가) 한 걸음 다가옵니다. 당신은 작은 숨소리와 몸짓을 살핍니다. 그리피스는 드래곤 마스터의 첫 기술은 명령이 아니라 듣는 것이라고 알려 줍니다.',
   '그리피스',
   '[{"label":"드래곤의 속도에 맞춘다","next_node":"training","state_changes":{"Bond":2}},{"label":"함께 연습할 곳을 찾는다","next_node":"training","state_changes":{"Courage":1}}]'::jsonb,
   '{}'::jsonb, '{"items":{"bonding_token":1}}'::jsonb, false, true),
  ('my_dragon', 'training', 4, 'scene', '첫 연습', '자신의 드래곤과 함께하는 훈련.',
   '훈련장에 작은 장애물이 놓입니다. 보와 슈는 물을 이용해 길을 보여 주고, 아나와 케프리는 빛으로 방향을 비춥니다. 로리와 벌칸은 기다리며 응원합니다. 이제 당신과 {dragon}의 차례입니다.',
   '내레이터',
   '[{"label":"쉬운 길부터 함께 시도한다","next_node":"discovery","state_changes":{"Patience":2,"Bond":1}},{"label":"드래곤이 고른 길을 따른다","next_node":"discovery","state_changes":{"Trust":2,"Bond":1}}]'::jsonb,
   '{}'::jsonb, '{}'::jsonb, false, true),
  ('my_dragon', 'discovery', 5, 'scene', '우리만의 방식', '작은 성공을 발견합니다.',
   '{dragon}이(가) 자기만의 방법으로 장애물을 넘습니다. 다른 드래곤과 똑같이 할 필요가 없다는 것을 당신도 깨닫습니다. 동료들이 박수를 치고, {dragon}이(가) 다시 당신 곁으로 돌아옵니다.',
   '내레이터',
   '[{"label":"함께한 첫 성공을 기념한다","next_node":"promise","state_changes":{"Bond":2}}]'::jsonb,
   '{}'::jsonb, '{"stat_points":1}'::jsonb, false, true),
  ('my_dragon', 'promise', 6, 'scene', '함께 걷는 약속', '성장 이야기의 출발점.',
   '당신은 {dragon}에게 서두르지 않겠다고 약속합니다. 오늘은 첫 만남이었고, 내일부터는 함께 배우는 날입니다. 당신과 드래곤의 이야기는 이제 시작입니다.',
   '내레이터',
   '[{"label":"성장 이야기로 이어가기","next_node":null,"state_changes":{"Bond":1}}]'::jsonb,
   '{}'::jsonb, '{}'::jsonb, false, true),
  ('dragon_growth', 'check_in', 1, 'scene', '오늘의 상태', '드래곤의 변화를 살펴봅니다.',
   '당신은 {dragon}의 움직임과 표정을 살핍니다. 어제보다 자신 있게 걷는지, 잠시 쉬고 싶은지 알아차리는 것부터 오늘의 훈련이 시작됩니다.',
   '내레이터',
   '[{"label":"먼저 쉬며 살펴본다","next_node":"practice","state_changes":{"Patience":2}},{"label":"함께 가볍게 움직인다","next_node":"practice","state_changes":{"Trust":1}}]'::jsonb,
   '{}'::jsonb, '{}'::jsonb, true, true),
  ('dragon_growth', 'practice', 2, 'scene', '작은 목표', '한 단계씩 훈련합니다.',
   '그리피스는 오늘의 목표를 작게 정하라고 합니다. {dragon}이(가) 스스로 해낼 수 있는 만큼만 시도해 봅니다. 보, 아나, 로리는 옆에서 각자의 경험을 들려줍니다.',
   '그리피스',
   '[{"label":"한 번 더 연습한다","next_node":"setback","state_changes":{"Practice":2}},{"label":"성공한 부분을 먼저 칭찬한다","next_node":"setback","state_changes":{"Bond":2}}]'::jsonb,
   '{}'::jsonb, '{}'::jsonb, false, true),
  ('dragon_growth', 'setback', 3, 'scene', '잠시 멈춤', '실패도 성장의 일부입니다.',
   '{dragon}이(가) 목표 앞에서 멈춥니다. 당신은 실패라고 말하지 않고, 숨을 고르며 다시 시도할 방법을 함께 찾습니다.',
   '내레이터',
   '[{"label":"목표를 더 작게 나눈다","next_node":"breakthrough","state_changes":{"Patience":2,"Bond":1}},{"label":"드래곤이 먼저 움직일 때까지 기다린다","next_node":"breakthrough","state_changes":{"Trust":2,"Bond":1}}]'::jsonb,
   '{}'::jsonb, '{}'::jsonb, false, true),
  ('dragon_growth', 'breakthrough', 4, 'scene', '조금 더 멀리', '함께 이룬 변화.',
   '이번에는 {dragon}이(가) 스스로 한 걸음 더 나아갑니다. 어제보다 멀리 간 것은 드래곤 혼자도, 당신 혼자도 아닙니다. 서로의 신호를 믿었기 때문입니다.',
   '내레이터',
   '[{"label":"오늘의 성장을 기록한다","next_node":"celebration","state_changes":{"Bond":2}}]'::jsonb,
   '{}'::jsonb, '{"stat_points":1,"items":{"bonding_token":1}}'::jsonb, false, true),
  ('dragon_growth', 'celebration', 5, 'scene', '함께 성장한 날', '다음 훈련을 기다립니다.',
   '훈련이 끝난 뒤 당신은 {dragon}과(와) 나란히 앉습니다. 다음에는 무엇을 배울지 아직 모릅니다. 다만 오늘의 작은 변화가 둘만의 이야기에 남았습니다.',
   '내레이터',
   '[{"label":"오늘의 이야기 마치기","next_node":null,"state_changes":{"Bond":1}}]'::jsonb,
   '{}'::jsonb, '{}'::jsonb, false, true)
ON CONFLICT DO NOTHING;
